name: aviz
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dartz: 0.10.1
  dio: ^5.1.2
  get_it: ^8.0.1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  cached_network_image: ^3.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  zarinpal: ^2.0.0
  translator: ^1.0.0
  url_launcher: ^6.3.1
  loading_indicator: ^3.1.0
  flutter_spinkit: ^5.2.1
  persian_number_utility: ^1.1.4
  smooth_page_indicator: ^1.2.0+3
  switcher_button: ^0.0.4
  mobkit_dashed_border: ^0.0.6
  dotted_dashed_line: ^0.0.3
  flutter_svg: ^2.0.10+1
  percent_indicator: ^4.2.2
  timeago: ^3.7.0
  image_picker: ^1.1.2
  image_cropper: ^8.0.0
  http_parser: ^4.0.0
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.3
  device_preview: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.2.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: SM
      fonts:
        - asset: assets/fonts/ShabnamMedium.ttf
    - family: SB
      fonts:
        - asset: assets/fonts/ShabnamBold.ttf
    - family: dana
      fonts:
        - asset: assets/fonts/dana.ttf
